server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/DB_microservice"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: 127.0.0.1
      port: 6379

app:
  services:
    profile: http://localhost:8081/profile

jwt:
  secret: daycaidaynaychinhlakhoabimatcuabandungdelorangoaidaynhenguyhiemchetnguoidayhihihi

